name: Generate Directory Markdown

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Directory Tree Generator
        uses: DenizAltunkapan/directory-tree-generator@v2
        with:
          path: "backend,frontend"
          extensions: ".java,.html,.ts,.scss"
          show-extensions: true

      - name: Commit changes if there are any
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add DIRECTORY.md
          if ! git diff --cached --quiet; then
            git commit -m "Update DIRECTORY.md"
          else
            echo "No changes to commit"
          fi

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.TOKEN_DENIZ }}
          branch: dependabot/directory-update
          base: main
          title: "Bump directory structure (auto-generated)"
          body: "This PR updates DIRECTORY.md automatically."
          draft: false
